# Generated by Django 6.0.5 on 2026-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_films_link_alter_films_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Animation', 'Animation'), ('Documentary', 'Documentary')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
