# Generated by Django 6.0.5 on 2026-06-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_films_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='genre',
        ),
    ]
