# Generated by Django 6.0.5 on 2026-06-16 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_films_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_films', to=settings.AUTH_USER_MODEL),
        ),
    ]
