# Generated by Django 6.0.5 on 2026-06-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_films_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
