# Generated by Django 6.0.5 on 2026-06-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.RemoveField(
            model_name='films',
            name='comment',
        ),
    ]
